version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: launchpad-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: launchpad-pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
